version: '3.9'

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        command: pdm run python3 cli.py
        expose:
            - 8000
        ports:
            - "8000:8000"
        env_file:
            -   ./.env.prod
        networks:
            - backend
        depends_on:
            -   db
    db:
        image: postgres:14.1
        volumes:
            -   asbp_db:/var/lib/postgresql/data/
        env_file:
            -   ./.env.prod
        networks:
            - backend

networks:
  backend:

volumes:
    asbp_db:
